

export const STORE_TASKS = 'STORE_TASKS';
export const STORE_COMPLETED_TASKS = 'STORE_COMPLETED_TASKS';
export const STORE_CURRENT_TASKS = 'STORE_CURRENT_TASKS';
export const UPDATE_CURRENT_TASKS = 'UPDATE_CURRENT_TASKS';

export const ADD_NEW_TASK = 'ADD_NEW_TASK';

export const START_PROGRESS = 'START_PROGRESS';
export const END_PROGRESS = 'END_PROGRESS';

export const AUTH_START = 'AUTH_START';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_STORE_USER = 'AUTH_STORE_USER';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';
export const AUTH_CLEAR_SIGNUP = 'AUTH_CLEAR_SIGNUP';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
